DROP DATABASE IF EXISTS templateDev;
CREATE DATABASE IF NOT EXISTS templateDev;
use templateDev;

DROP TABLE IF EXISTS User;
CREATE TABLE IF NOT EXISTS User(
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(100) NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    pwd VARCHAR(16000) NOT NULL,
    PRIMARY KEY (id)
);



